url: https://cibim.eng.ox.ac.uk
baseurl:
# Fill in your Google Analytics ID to track your website using GA
google_analytics: "UA-118303437-1"

# Site settings
title: CIBIM Lab
email: maarten.devos@eng.ox.ac.uk
description: "Led by Prof. Maarten De Vos, we are based at the Institute of Biomedical Engineering and are part of the Department of Engineering Science at the University of Oxford. The emphasis of the group is on engineering intelligent solutions for perinatal care; sleep monitoring and mobile, real-life brain monitoring. Our group applies advanced signal processing and machine learning techniques to enhance our understanding of the human brain, to develop rehabilitation strategies and to provide (semi-) automated decision support systems for patient monitoring in different fields. As medical data is often highly dimensional, multimodal and temporally dense, particular focus is on mining these available biotensors with a variety of data-driven tensor methods and tensor fusion. We work in a truly interdisciplinary environment, having collaborations with world-leading clinicians from the Oxford University Hospitals NHS Trust, fMRIB, the Oxford Centre for Affordable Healthcare at Kellogg College, and the Sleep, Circadian and Neuroscience Institute (SCNi) to address unmet clinical needs. As the goal of each project is to directly impact clinical care, particular focus is on the implementation of new biomedical technologies through large clinical trials and technology transfer into available products"

google_analytics: "UA-118303437-1"

# Team names, titles and social links
people:
- name: Prof. Maarten De Vos
  pic: maarten
  position: Group Leader
  social:
    - title: google
      url: https://scholar.google.co.uk/citations?user=xTjDXdQAAAAJ&hl=en&oi=ao
    - title: envelope
      url: maarten.devos@eng.ox.ac.uk

- name: Jorne Laton
  pic: jorne
  position: Postdoctoral Researcher
  social:
    - title: envelope
      url: mailto:jorne.laton@eng.ox.ac.uk
      
- name: Suzanne Ftouni
  pic: suzanne
  position: Postdoctoral Researcher
  social:
    - title: envelope
      url: mailto:suzanne.ftouni@ndcn.ox.ac.uk
    - title: linkedin
      url: https://www.linkedin.com/in/suzanne-ftouni-43a0984a/
      
- name: Kirubin Pillay
  pic: kirubin
  position: DPhil Student
  social:
    - title: envelope
      url: mailto:placeholder

- name: Navin Cooray
  pic: navin
  position: DPhil Student
  social:
    - title: envelope
      url: mailto:navin.cooray@eng.ox.ac.uk
    - title: linkedin
      url: https://www.linkedin.com/in/navincooray

- name: Oliver Carr
  pic: oliver
  position: DPhil Student
  social:
    - title: envelope
      url: mailto:placeholder

- name: Andrew Creagh
  pic: andrew
  position: DPhil Student
  social:
    - title: envelope
      url: mailto:andrew.creagh@eng.ox.ac.uk
    - title: linkedin
      url: https://www.linkedin.com/in/andrewcreagh
    - title: twitter
      url: https://twitter.com/creagha

- name: Stefan Bostock
  pic: stefan
  position: DPhil Student
  social:
    - title: envelope
      url: mailto:placeholder
      
- name: Oliver Y. Chen
  pic: placeholder
  position: DPhil Student
  social:
    - title: envelope
      url: mailto:yibin.chen@seh.ox.ac.uk
      
- name: Guy Nagels
  pic: placeholder
  position: DPhil Student
  social:
    - title: envelope
      url: mailto:guy.nagels@seh.ox.ac.uk
      
 - name: Christian Harding
  pic: placeholder
  position: DPhil Student
  social:
    - title: envelope
      url: mailto:christian.harding@sjc.ox.ac.uk
      
- name: Erin Coonahan
  pic: erin
  position: DPhil Student
  social:
    - title: envelope
      url: mailto:erin.coonahan@linacre.ox.ac.uk
      
formerpeople:

- name: Fernando Andreotti
  pic: fernando
  position: Postdoctoral Researcher

- name: Huy Phan
  pic: huy
  position: Postdoctoral Researcher
  
- name: Niclas Palmius
  pic: niclas
  position: Postdoctoral Researcher
  
- name: Elina Naydenova
  pic: elina
  position:  DPhil Student
  
- name: John Prince
  pic: john
  position: DPhil Student
 
- name: Maximilian Strobl
  pic: maximilian
  position: DPhil Student

- name: Gabrielle Cretot-Richert
  pic: gabrielle
  position: Visiting PhD Student

- name: Kaare Mikkelsen
  pic: kaare
  position: Visiting Postdoc
     
- name: Awais M. Kamboh
  pic: awais
  position: Visiting Professor
  
- name: Amir Hossein Ansari
  pic: amir
  position: Visiting PhD Student
  
- name: Andre

- name: Luba
  
# Social networks usernames (many more available: envelope, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
#   social:
#   - title: twitter
#   url: http://twitter.com/CIBIM_lab
#  - title: facebook
#    url:
# - title: stack-overflow
#   url: http://stackoverflow.com/questions/tagged/cibim
# - title: bitbucket
#   url: http://bitbucket.org/jekyll
# - title: github
#   url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address: University of Oxford <br> Old Road Campus Research Building <br> OX3 7DQ - Oxford <br> United Kingdom

# Build settings
markdown: kramdown
permalink: pretty

# Plugins
plugins: ['jekyll-twitter-plugin']
