url: https://fernandoandreotti.github.io
baseurl: /cibim/

# Site settings
title: CIBIM Lab
email: maarten.devos@eng.ox.ac.uk
description: "CIBIM Lab"


# Team names, titles and social links
people:
- name: Prof. Maarten De Vos
  pic: maarten
  position: Group Leader
  social:
    - title: google
      url: https://scholar.google.co.uk/citations?user=xTjDXdQAAAAJ&hl=en&oi=ao
    - title: envelope
      url: maarten.devos@eng.ox.ac.uk

- name: Niclas Palmius
  pic: placeholder
  position: Postdoctoral Researcher
  social:
    - title: envelope
      url: mailto:niclas.palmius@eng.ox.ac.uk

- name: Fernando Andreotti
  pic: fernando
  position: Postdoctoral Researcher
  social:
    - title: external-link
      url: http://fernando.planetarium.com.br/
    - title: google
      url: https://scholar.google.com/citations?user=rajtyxUAAAAJ&hl=en
    - title: envelope
      url: mailto:fernando.andreotti@eng.ox.ac.uk

- name: Kaare Mikkelsen
  pic: placeholder
  position: Visiting Postdoctoral Researcher
  social:
    - title: google
      url: https://scholar.google.co.uk/citations?user=DL5CvZoAAAAJ&hl=en&oi=ao
    - title: envelope
      url: mailto:mikkelsen.kaare@gmail.com

- name: Elina Naydenova
  pic: placeholder
  position:  DPhil Student
  social:
    - title: envelope
      url: mailto:elina.naydenova@univ.ox.ac.uk

- name: John Prince
  pic: placeholder
  position: DPhil Student
  social:
    - title: envelope
      url: mailto:john.prince@eng.ox.ac.uk

- name: Kirubin Pillay
  pic: placeholder
  position: DPhil Student
  social:
    - title: envelope
      url: mailto:kirubin.pillay@stcatz.ox.ac.uk

- name: Navin Cooray
  pic: placeholder
  position: DPhil Student
  social:
    - title: envelope
      url: mailto:navin.cooray@eng.ox.ac.uk

- name: Oliver Carr
  pic: placeholder
  position: DPhil Student
  social:
    - title: envelope
      url: mailto:oliver.carr@eng.ox.ac.uk

- name: Andrew Creagh
  pic: placeholder
  position: DPhil Student
  social:
    - title: envelope
      url: mailto:andrew.creagh@eng.ox.ac.uk

# Social networks usernames (many more available: envelope, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/CIBIM_lab
#  - title: facebook
#    url:
# - title: stack-overflow
#   url: http://stackoverflow.com/questions/tagged/cibim
# - title: bitbucket
#   url: http://bitbucket.org/jekyll
# - title: github
#   url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: University of Oxford
  - line: Old Road Campus Research Building,
  - line: Oxford - OX3 7DQ
  - line: United Kingdom

# Build settings
markdown: kramdown
permalink: pretty
