url: https://fernandoandreotti.github.io
baseurl: /cibim/

# Site settings
title: CIBIM Lab
email: maarten.devos@eng.ox.ac.uk
description: "CIBIM Lab"


# Team names, titles and social links
people:
- name: Prof. Maarten De Vos
  pic: maarten
  position: Group Leader
  social:
    - title: google
      url: https://scholar.google.co.uk/citations?user=xTjDXdQAAAAJ&hl=en&oi=ao
    - title: envelope
      url: maarten.devos@eng.ox.ac.uk

- name: Niclas Palmius
  pic: placeholder
  position: Postdoctoral Researcher

- name: Fernando Andreotti
  pic: fernando
  position: Postdoctoral Researcher
  social:
    - title: google
      url: https://scholar.google.com/citations?user=rajtyxUAAAAJ&hl=en
    - title: envelope
      url: mailto:fernando.andreotti@eng.ox.ac.uk

- name: Kaare Mikkelsen
  pic: kaare
  position: Postdoctoral Researcher
  social:
    - title: google
      url: https://scholar.google.co.uk/citations?user=DL5CvZoAAAAJ&hl=en&oi=ao

- name: Elina Naydenova
  pic: elina
  position:  DPhil Student

- name: John Prince
  pic: placeholder
  position: DPhil Student

- name: Kirubin Pillay
  pic: placeholder
  position: DPhil Student

- name: Navin Cooray
  pic: navin
  position: DPhil Student

- name: Oliver Carr
  pic: placeholder
  position: DPhil Student

- name: Andrew Creagh
  pic: placeholder
  position: DPhil Student

- name: Gabrielle Cretot-Richert
  pic: gabrielle
  position: Visiting PhD Student

- name: Stefan Bostock
  pic: placeholder
  position: DPhil Student


# Social networks usernames (many more available: envelope, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/CIBIM_lab
#  - title: facebook
#    url:
# - title: stack-overflow
#   url: http://stackoverflow.com/questions/tagged/cibim
# - title: bitbucket
#   url: http://bitbucket.org/jekyll
# - title: github
#   url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address: University of Oxford <br> Old Road Campus Research Building <br> OX3 7DQ - Oxford <br> United Kingdom

# Build settings
markdown: kramdown
permalink: pretty
